# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IiiKY6hp7XU-Hdod0PMGxpo-M7X6YaA-
"""

import streamlit as st
import matplotlib.pyplot as plt
import numpy as np
from fpdf import FPDF
import tempfile
import os

# Titulek aplikace
st.set_page_config(page_title="Body na kružnici", layout="centered")
st.title("🟢 Body na kružnici")

# Vstupní parametry
st.sidebar.header("🎛️ Parametry")
x0 = st.sidebar.number_input("X souřadnice středu", value=0.0)
y0 = st.sidebar.number_input("Y souřadnice středu", value=0.0)
r = st.sidebar.number_input("Poloměr kružnice", value=1.0, min_value=0.01)
n = st.sidebar.slider("Počet bodů", min_value=3, max_value=100, value=10)
barva = st.sidebar.color_picker("Barva bodů", "#FF0000")
jednotka = st.sidebar.selectbox("Jednotka", ["m", "cm", "mm"])

# Výpočet bodů
theta = np.linspace(0, 2*np.pi, n, endpoint=False)
x = x0 + r * np.cos(theta)
y = y0 + r * np.sin(theta)

# Vykreslení grafu
fig, ax = plt.subplots()
ax.scatter(x, y, color=barva, label="Body")
ax.set_aspect('equal')
ax.set_xlabel(f"X ({jednotka})")
ax.set_ylabel(f"Y ({jednotka})")
ax.grid(True)
ax.set_title("Rozložení bodů na kružnici")
st.pyplot(fig)

# Informace o aplikaci
with st.expander("ℹ️ O aplikaci"):
    st.markdown("""
    **Autor:** Jan Novák
    **Kontakt:** jan.novak@example.com
    **Použité technologie:**
    - Python
    - Streamlit
    - Matplotlib
    - FPDF
    """)

# Export do PDF
if st.button("🖨️ Exportovat do PDF"):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt="Parametry úlohy - Body na kružnici", ln=True, align='C')
    pdf.ln(10)
    pdf.cell(200, 10, txt=f"Střed: ({x0}, {y0})", ln=True)
    pdf.cell(200, 10, txt=f"Poloměr: {r} {jednotka}", ln=True)
    pdf.cell(200, 10, txt=f"Počet bodů: {n}", ln=True)
    pdf.cell(200, 10, txt=f"Barva bodů: {barva}", ln=True)
    pdf.cell(200, 10, txt="Autor: Jan Novák", ln=True)
    pdf.cell(200, 10, txt="Kontakt: jan.novak@example.com", ln=True)

    # Uložení do dočasného souboru
    with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmpfile:
        pdf.output(tmpfile.name)
        st.download_button("📥 Stáhnout PDF", data=open(tmpfile.name, "rb").read(), file_name="kruznice.pdf", mime="application/pdf")
        os.unlink(tmpfile.name)